### ISSUE TITLE
lab 1

### ISSUE THREAD

**Issue by egrinberg** [SENECA-DSA555/dsa555-w19#2]
https://github.com/SENECA-DSA555/dsa555-w19/blob/b596ff5fc1308bf54d8e2518cbdfdfd6422d8a32/lab1.cpp#L3-L5

**Comment by catherine-leung** [comment]
https://github.com/SENECA-DSA555/dsa555-w19/blob/b596ff5fc1308bf54d8e2518cbdfdfd6422d8a32/lab1.cpp#L3-L5

**Comment by khong10** [comment]
https://github.com/SENECA-DSA555/dsa555-w19/blob/b596ff5fc1308bf54d8e2518cbdfdfd6422d8a32/lab1.cpp#L3-L5
