### ISSUE TITLE
Inconsistency in unordered/ordered list in lab1wiki.md

### ISSUE THREAD

**Issue by ArFe** [SENECA-DSA555/dsa555-w19#8]
In the file lab1wiki.md, it is requested to have a unordered list inside and unordered list:
> item 1 in an unordered list
> item 2 in an unordered list
> item 3 in an unordered list
> item 1 in an unordered sublist of under item 3
> item 2 in an unordered sublist of under item 3
> item 4 in an unordered list

However, in the video presented as a model the nested list is actually ordered:
![image](https://user-images.githubusercontent.com/12927701/51156867-7ff6b800-184b-11e9-8e13-491d2b6678d8.png)

**Comment by catherine-leung** [comment]
ah should be ordered list on that second one.  Good catch I'll fix it.
